apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::691386878310:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DS4BCEZ2FX1B
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::691386878310:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-05T22:18:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1564"
  uid: 16634955-e2d4-4286-9800-94aa15534935
